### ISSUE TITLE
'Board' object has no attribute 'outcome'

### ISSUE THREAD

**Issue by barvinog** [asdfjkl/neural_network_chess#5]
I just executed python mcts.py and received an error message:
34
0
Traceback (most recent call last):
  File "mcts.py", line 134, in <module>
    payout = simulate(node)
  File "mcts.py", line 63, in simulate
    while(board.outcome(claim_draw = True) == None):
AttributeError: 'Board' object has no attribute 'outcome'

**Comment by barvinog** [comment]
Please help me run the script

**Comment by asdfjkl** [comment]
looks to me as if you are using a very old version of python-chess?

This was tested with python-chess 1.999. I am using python 3.8 and python chess was installed with `pip install pychon-chess`

**Comment by barvinog** [comment]
I'm also using 1.999 and still getting 'Board' object has no attribute 'outcome' error message

**Comment by asdfjkl** [comment]
There is apparently something wrong with your setup. This is working on a fresh Ubuntu 20.04:

`git clone https://github.com/asdfjkl/neural_network_chess.git`
`cd neural_network_chess`
`cd chapter_03`
`sudo apt install python3`
`pip3 install --user python-chess`
`python3 mcts.py`

**Comment by asdfjkl** [comment]
(I guess this can be closed)
